### ISSUE TITLE
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: user'

### ISSUE THREAD

**Issue by moggiex** [NullRefExcep/yii2-full-admin#1]
Howdy, 

A fresh install of Yii2 basic and after running the command:

`composer require --prefer-dist nullref/yii2-full-admin "*"`

And then, this for a second time as the installed_modules.php file is not created automatically,. so added `<?php return [];` to it:

`php yii module/install nullref/yii2-full-admin`

I get this message, the same happens for your other modules too. 

**Any ideas?**

```
D:\xampp7\htdocs\yii-play\basic>php yii module/install nullref/yii2-full-admin
 Module "user" installing:
Rewrite exist config? (yes|no) [no]:yes
Module config was rewrote
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: user'

in D:\xampp7\htdocs\yii-play\basic\vendor\nullref\yii2-core\src\components\ModuleInstaller.php:81

Stack trace:
#0 D:\xampp7\htdocs\yii-play\basic\vendor\nullref\yii2-core\src\components\ModuleInstaller.php(81): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'D:\\xampp7\\htdoc...', 81, Array)
#1 D:\xampp7\htdocs\yii-play\basic\vendor\nullref\yii2-full-admin\src\Installer.php(32): nullref\core\components\ModuleInstaller->install()
#2 D:\xampp7\htdocs\yii-play\basic\vendor\nullref\yii2-core\src\console\ModuleController.php(39): nullref\fulladmin\Installer->install()
#3 D:\xampp7\htdocs\yii-play\basic\vendor\nullref\yii2-core\src\console\ModuleController.php(31): nullref\core\console\ModuleController->runInstallerCommand('nullref/yii2-fu...', 'install', 'Module module w...')
#4 [internal function]: nullref\core\console\ModuleController->actionInstall('nullref/yii2-fu...')
#5 D:\xampp7\htdocs\yii-play\basic\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#6 D:\xampp7\htdocs\yii-play\basic\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 D:\xampp7\htdocs\yii-play\basic\vendor\yiisoft\yii2\console\Controller.php(144): yii\base\Controller->runAction('install', Array)
#8 D:\xampp7\htdocs\yii-play\basic\vendor\yiisoft\yii2\base\Module.php(528): yii\console\Controller->runAction('install', Array)
#9 D:\xampp7\htdocs\yii-play\basic\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('module/install', Array)
#10 D:\xampp7\htdocs\yii-play\basic\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('module/install', Array)
#11 D:\xampp7\htdocs\yii-play\basic\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 D:\xampp7\htdocs\yii-play\basic\yii(20): yii\base\Application->run()
#13 {main}
```

**Comment by ZAYEC77** [comment]
Hello
I think you need to create a file in config dir like this:
https://github.com/NullRefExcep/yii2-boilerplate/blob/master/src/config/installed_modules.php

if it doesn't help, try to add module config manually and run migration by the command `php yii modules-migrate`

**Comment by moggiex** [comment]
Howdy, yep have tried that, no difference.

Try it for yourself on a fresh install and you'll have the same issue I'm sure, 

Matt

**Comment by ZAYEC77** [comment]
Sorry for delay, 'll check it soon

**Comment by ZAYEC77** [comment]
@moggiex 
i think it possible that you didn't add `installed_modules.php` file to config as part of modules definition.

something like this:
you have files:
- installed_modules.php
```php
<?php return [];
```
- modules.php
```php
<?php 
$config = require(__DIR__ . '/installed_modules.php');
return array_merge($config, []);
```
- web.php
```php
<?php
$modules = require(__DIR__ . '/modules.php');
$config = [
//...
    'modules' => $modules,
//...
];
return $config;
```

I use scructure like this in my projects. 
It works.

**Comment by dimonpvt1236** [comment]
you also should add modules section in console.php file
